[2025-05-19T10:14:25.821+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: math_crawler_pipeline.save_to_bigquery manual__2025-05-19T09:23:32.331846+00:00 [queued]>
[2025-05-19T10:14:25.832+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: math_crawler_pipeline.save_to_bigquery manual__2025-05-19T09:23:32.331846+00:00 [queued]>
[2025-05-19T10:14:25.833+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-05-19T10:14:25.834+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 3
[2025-05-19T10:14:25.834+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-05-19T10:14:25.844+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): save_to_bigquery> on 2025-05-19 09:23:32.331846+00:00
[2025-05-19T10:14:25.851+0000] {standard_task_runner.py:55} INFO - Started process 507 to run task
[2025-05-19T10:14:25.855+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'math_crawler_pipeline', 'save_to_bigquery', 'manual__2025-05-19T09:23:32.331846+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/MathDag.py', '--cfg-path', '/tmp/tmp5dhlrpve']
[2025-05-19T10:14:25.858+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask save_to_bigquery
[2025-05-19T10:14:25.902+0000] {task_command.py:389} INFO - Running <TaskInstance: math_crawler_pipeline.save_to_bigquery manual__2025-05-19T09:23:32.331846+00:00 [running]> on host 23e48ed0cd15
[2025-05-19T10:14:25.947+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=math_crawler_pipeline
AIRFLOW_CTX_TASK_ID=save_to_bigquery
AIRFLOW_CTX_EXECUTION_DATE=2025-05-19T09:23:32.331846+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-19T09:23:32.331846+00:00
[2025-05-19T10:14:28.987+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:14:31.989+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:14:34.993+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:14:34.994+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:14:34.994+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 1: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:14:38.002+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:14:41.004+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:14:44.008+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:14:44.008+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:14:44.009+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 2: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:14:47.014+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:14:50.019+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:14:53.025+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:14:53.026+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:14:53.027+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 3: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:14:56.032+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:14:59.037+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:02.042+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:02.042+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:02.043+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 4: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:05.048+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:08.050+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:11.054+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:11.055+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:11.055+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 5: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:14.060+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:17.065+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:20.070+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:20.071+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:20.071+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 6: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:23.078+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:26.079+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:29.081+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:29.082+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:29.083+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 7: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:32.088+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:35.093+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:38.097+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:38.098+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:38.098+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 8: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:41.102+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:44.106+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:47.111+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:47.111+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:47.112+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 9: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:50.116+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:15:53.123+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:15:56.127+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:15:56.127+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:15:56.127+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 10: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:15:59.132+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:02.133+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:05.137+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:05.138+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:05.138+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 11: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:08.144+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:11.148+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:14.150+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:14.151+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:14.151+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 12: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:17.156+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:20.158+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:23.163+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:23.164+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:23.164+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 13: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:26.168+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:29.170+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:32.173+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:32.174+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:32.174+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 14: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:35.178+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:38.185+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:41.190+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:41.190+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:41.190+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 15: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:44.195+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:47.198+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:50.202+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:50.203+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:50.203+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 16: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:16:53.209+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:16:56.214+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:16:59.220+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:16:59.220+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:16:59.221+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 17: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:02.226+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:05.231+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:08.236+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:08.236+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:08.237+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 18: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:11.241+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:14.244+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:17.250+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:17.250+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:17.250+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 19: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:20.255+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:23.261+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:26.271+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:26.271+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:26.272+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 20: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:29.278+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:32.282+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:35.286+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:35.286+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:35.286+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 21: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:38.290+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:41.295+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:44.299+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:44.299+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:44.300+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 22: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:47.304+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:50.308+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:17:53.312+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:17:53.312+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:17:53.312+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 23: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:17:56.316+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:17:59.319+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:02.323+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:02.324+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:02.324+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 24: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:05.328+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:08.332+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:11.333+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:11.334+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:11.334+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 25: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:14.338+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:17.342+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:20.347+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:20.348+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:20.348+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 26: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:23.354+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:26.356+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:29.360+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:29.360+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:29.361+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 27: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:32.365+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:35.370+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:38.374+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:38.375+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:38.375+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 28: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:41.380+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:44.384+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:47.388+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:47.388+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:47.389+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 29: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:50.393+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:18:53.401+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:18:56.405+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:18:56.405+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:18:56.405+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 30: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:18:59.410+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:02.415+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:05.419+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:05.419+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:05.419+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 31: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:08.424+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:11.428+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:14.432+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:14.432+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:14.432+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 32: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:17.437+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:20.441+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:23.447+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:23.448+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:23.448+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 33: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:26.452+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:29.455+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:32.459+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:32.460+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:32.461+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 34: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:35.466+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:38.470+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:41.475+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:41.476+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:41.476+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 35: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:44.480+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:47.484+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:50.488+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:50.489+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:50.489+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 36: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:19:53.495+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:19:56.499+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:19:59.503+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:19:59.503+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:19:59.504+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 37: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:02.508+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:05.512+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:08.516+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:08.516+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:08.517+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 38: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:11.521+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:14.525+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:17.529+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:17.529+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:17.530+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 39: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:20.532+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:23.538+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:26.542+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:26.542+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:26.542+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 40: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:29.547+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:32.552+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:35.556+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:35.556+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:35.557+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 41: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:38.561+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:41.565+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:44.570+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:44.570+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:44.570+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 42: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:47.575+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:50.579+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:20:53.584+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:20:53.584+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:20:53.585+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 43: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:20:56.589+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:20:59.593+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:02.597+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:02.597+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:02.598+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 44: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:05.602+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:08.606+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:11.610+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:11.610+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:11.611+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 45: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:14.612+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:17.614+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:20.618+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:20.619+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:20.619+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 46: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:23.625+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:26.628+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:29.632+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:29.632+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:29.632+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 47: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:32.637+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:35.641+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:38.645+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:38.645+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:38.646+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 48: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:41.650+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:44.652+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:47.657+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:47.657+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:47.657+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 49: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:50.662+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:21:53.665+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:21:56.669+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:21:56.670+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:21:56.670+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 50: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:21:59.673+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:02.675+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:05.680+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:05.681+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:05.681+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 51: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:08.682+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:11.686+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:14.688+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:14.689+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:14.689+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 52: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:17.691+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:20.695+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:23.700+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:23.700+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:23.700+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 53: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:26.702+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:29.706+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:32.710+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:32.710+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:32.710+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 54: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:35.715+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:38.720+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:41.722+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:41.722+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:41.722+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 55: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:44.727+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:47.730+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:50.731+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:50.732+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:50.732+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 56: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:22:53.737+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:22:56.742+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:22:59.745+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:22:59.746+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:22:59.746+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 57: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:02.750+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:05.755+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:08.759+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:08.759+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:08.760+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 58: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:11.761+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:14.765+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:17.769+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:17.770+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:17.771+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 59: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:20.775+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:23.780+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:26.782+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:26.783+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:26.783+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 60: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:29.787+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:32.792+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:35.794+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:35.795+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:35.795+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 61: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:38.799+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:41.803+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:44.804+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:44.805+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:44.805+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 62: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:47.809+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:50.810+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:23:53.814+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:23:53.815+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:23:53.815+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 63: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:23:56.819+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2025-05-19T10:23:59.823+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2025-05-19T10:24:02.828+0000] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: timed out
[2025-05-19T10:24:02.829+0000] {_default.py:301} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2025-05-19T10:24:02.829+0000] {MathDag.py:75} ERROR - Lỗi lưu BigQuery cho link 64: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
[2025-05-19T10:24:02.829+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-05-19T10:24:02.836+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=math_crawler_pipeline, task_id=save_to_bigquery, execution_date=20250519T092332, start_date=20250519T101425, end_date=20250519T102402
[2025-05-19T10:24:02.886+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-05-19T10:24:02.903+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
